name: Create Release on flag
on:
  push:
    branches: [ main ]

jobs:
  release:
    if: contains(github.event.head_commit.message, '-r')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep -oE "version '\d+\.\d+\.\d+'" fxmanifest.lua | cut -d"'" -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          body: |
